/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as BilibiliRouteImport } from './routes/bilibili'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as GlassRouteImport } from './routes/glass'
import { Route as GmailRouteImport } from './routes/gmail'
import { Route as QuickPanelRouteImport } from './routes/quick-panel'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as SessionRouteImport } from './routes/session'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as SessionIndexRouteImport } from './routes/session.index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliRoute = BilibiliRouteImport.update({
  id: '/bilibili',
  path: '/bilibili',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassRoute = GlassRouteImport.update({
  id: '/glass',
  path: '/glass',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailRoute = GmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickPanelRoute = QuickPanelRouteImport.update({
  id: '/quick-panel',
  path: '/quick-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionRoute,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/bilibili': typeof BilibiliRoute
  '/formations': typeof FormationsRoute
  '/glass': typeof GlassRoute
  '/gmail': typeof GmailRoute
  '/quick-panel': typeof QuickPanelRoute
  '/scheduled': typeof ScheduledRoute
  '/session': typeof SessionRouteWithChildren
  '/trending': typeof TrendingRoute
  '/usage': typeof UsageRoute
  '/workbench': typeof WorkbenchRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/bilibili': typeof BilibiliRoute
  '/formations': typeof FormationsRoute
  '/glass': typeof GlassRoute
  '/gmail': typeof GmailRoute
  '/quick-panel': typeof QuickPanelRoute
  '/scheduled': typeof ScheduledRoute
  '/trending': typeof TrendingRoute
  '/usage': typeof UsageRoute
  '/workbench': typeof WorkbenchRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session': typeof SessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/bilibili': typeof BilibiliRoute
  '/formations': typeof FormationsRoute
  '/glass': typeof GlassRoute
  '/gmail': typeof GmailRoute
  '/quick-panel': typeof QuickPanelRoute
  '/scheduled': typeof ScheduledRoute
  '/session': typeof SessionRouteWithChildren
  '/trending': typeof TrendingRoute
  '/usage': typeof UsageRoute
  '/workbench': typeof WorkbenchRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/bilibili'
    | '/formations'
    | '/glass'
    | '/gmail'
    | '/quick-panel'
    | '/scheduled'
    | '/session'
    | '/trending'
    | '/usage'
    | '/workbench'
    | '/session/$sessionId'
    | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/bilibili'
    | '/formations'
    | '/glass'
    | '/gmail'
    | '/quick-panel'
    | '/scheduled'
    | '/trending'
    | '/usage'
    | '/workbench'
    | '/session/$sessionId'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/bilibili'
    | '/formations'
    | '/glass'
    | '/gmail'
    | '/quick-panel'
    | '/scheduled'
    | '/session'
    | '/trending'
    | '/usage'
    | '/workbench'
    | '/session/$sessionId'
    | '/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  BilibiliRoute: typeof BilibiliRoute
  FormationsRoute: typeof FormationsRoute
  GlassRoute: typeof GlassRoute
  GmailRoute: typeof GmailRoute
  QuickPanelRoute: typeof QuickPanelRoute
  ScheduledRoute: typeof ScheduledRoute
  SessionRoute: typeof SessionRouteWithChildren
  TrendingRoute: typeof TrendingRoute
  UsageRoute: typeof UsageRoute
  WorkbenchRoute: typeof WorkbenchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili': {
      id: '/bilibili'
      path: '/bilibili'
      fullPath: '/bilibili'
      preLoaderRoute: typeof BilibiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glass': {
      id: '/glass'
      path: '/glass'
      fullPath: '/glass'
      preLoaderRoute: typeof GlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail': {
      id: '/gmail'
      path: '/gmail'
      fullPath: '/gmail'
      preLoaderRoute: typeof GmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-panel': {
      id: '/quick-panel'
      path: '/quick-panel'
      fullPath: '/quick-panel'
      preLoaderRoute: typeof QuickPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof SessionRoute
    }
  }
}

interface SessionRouteChildren {
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SessionIndexRoute: typeof SessionIndexRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionSessionIdRoute: SessionSessionIdRoute,
  SessionIndexRoute: SessionIndexRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  BilibiliRoute: BilibiliRoute,
  FormationsRoute: FormationsRoute,
  GlassRoute: GlassRoute,
  GmailRoute: GmailRoute,
  QuickPanelRoute: QuickPanelRoute,
  ScheduledRoute: ScheduledRoute,
  SessionRoute: SessionRouteWithChildren,
  TrendingRoute: TrendingRoute,
  UsageRoute: UsageRoute,
  WorkbenchRoute: WorkbenchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
