/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BilibiliRouteImport } from './routes/bilibili'
import { Route as GmailRouteImport } from './routes/gmail'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as UsageRouteImport } from './routes/usage'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailRoute = GmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliRoute = BilibiliRouteImport.update({
  id: '/bilibili',
  path: '/bilibili',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliRoute
  '/gmail': typeof GmailRoute
  '/scheduled': typeof ScheduledRoute
  '/trending': typeof TrendingRoute
  '/usage': typeof UsageRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliRoute
  '/gmail': typeof GmailRoute
  '/scheduled': typeof ScheduledRoute
  '/trending': typeof TrendingRoute
  '/usage': typeof UsageRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliRoute
  '/gmail': typeof GmailRoute
  '/scheduled': typeof ScheduledRoute
  '/trending': typeof TrendingRoute
  '/usage': typeof UsageRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bilibili' | '/gmail' | '/scheduled' | '/trending' | '/usage' | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bilibili' | '/gmail' | '/scheduled' | '/trending' | '/usage' | '/session/$sessionId'
  id: '__root__' | '/' | '/bilibili' | '/gmail' | '/scheduled' | '/trending' | '/usage' | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilibiliRoute: typeof BilibiliRoute
  GmailRoute: typeof GmailRoute
  ScheduledRoute: typeof ScheduledRoute
  TrendingRoute: typeof TrendingRoute
  UsageRoute: typeof UsageRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail': {
      id: '/gmail'
      path: '/gmail'
      fullPath: '/gmail'
      preLoaderRoute: typeof GmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili': {
      id: '/bilibili'
      path: '/bilibili'
      fullPath: '/bilibili'
      preLoaderRoute: typeof BilibiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilibiliRoute: BilibiliRoute,
  GmailRoute: GmailRoute,
  ScheduledRoute: ScheduledRoute,
  TrendingRoute: TrendingRoute,
  UsageRoute: UsageRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
