/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as GmailRouteImport } from './routes/gmail'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as BilibiliRouteImport } from './routes/bilibili'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIndexRouteImport } from './routes/session.index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailRoute = GmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliRoute = BilibiliRouteImport.update({
  id: '/bilibili',
  path: '/bilibili',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/bilibili': typeof BilibiliRoute
  '/formations': typeof FormationsRoute
  '/gmail': typeof GmailRoute
  '/scheduled': typeof ScheduledRoute
  '/trending': typeof TrendingRoute
  '/usage': typeof UsageRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/bilibili': typeof BilibiliRoute
  '/formations': typeof FormationsRoute
  '/gmail': typeof GmailRoute
  '/scheduled': typeof ScheduledRoute
  '/trending': typeof TrendingRoute
  '/usage': typeof UsageRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session': typeof SessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/bilibili': typeof BilibiliRoute
  '/formations': typeof FormationsRoute
  '/gmail': typeof GmailRoute
  '/scheduled': typeof ScheduledRoute
  '/trending': typeof TrendingRoute
  '/usage': typeof UsageRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/bilibili'
    | '/formations'
    | '/gmail'
    | '/scheduled'
    | '/trending'
    | '/usage'
    | '/session/$sessionId'
    | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/bilibili'
    | '/formations'
    | '/gmail'
    | '/scheduled'
    | '/trending'
    | '/usage'
    | '/session/$sessionId'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/bilibili'
    | '/formations'
    | '/gmail'
    | '/scheduled'
    | '/trending'
    | '/usage'
    | '/session/$sessionId'
    | '/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  BilibiliRoute: typeof BilibiliRoute
  FormationsRoute: typeof FormationsRoute
  GmailRoute: typeof GmailRoute
  ScheduledRoute: typeof ScheduledRoute
  TrendingRoute: typeof TrendingRoute
  UsageRoute: typeof UsageRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SessionIndexRoute: typeof SessionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail': {
      id: '/gmail'
      path: '/gmail'
      fullPath: '/gmail'
      preLoaderRoute: typeof GmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili': {
      id: '/bilibili'
      path: '/bilibili'
      fullPath: '/bilibili'
      preLoaderRoute: typeof BilibiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/session'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  BilibiliRoute: BilibiliRoute,
  FormationsRoute: FormationsRoute,
  GmailRoute: GmailRoute,
  ScheduledRoute: ScheduledRoute,
  TrendingRoute: TrendingRoute,
  UsageRoute: UsageRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  SessionIndexRoute: SessionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
