import type {
  AgentDefinition,
  AgentListItem,
  AgentMutationResult,
  AnalyzeArticleResult,
  AnalyzeThreadInput,
  AnalyzeThreadResult,
  ArticleSummary,
  ArtifactEntry,
  Attachment,
  BiliAnalysis,
  BiliDeleteResult,
  BiliListResult,
  BiliLoginStatus,
  BiliProcessResult,
  BiliSaveResult,
  BiliSummary,
  BiliTranscribeProgress,
  BiliTranscribeResult,
  BiliVideo,
  CalendarConfigView,
  CalendarEvent,
  CalendarLocalInput,
  CollectedArticleWithAnalysis,
  CronJobSummary,
  CronRun,
  GmailThreadAnalysis,
  MemoryView,
  ObsidianConfig,
  PermissionDecision,
  RepoResearch,
  ResearchRepoResult,
  RunOptions,
  ScheduledTask,
  SessionSettings,
  SessionSummary,
  SubmitPromptResult,
  TranscriptionConfig,
  TrendingPeriod,
  TrendingRepo,
  UIEvent,
  UsageStats,
} from '@swarm/protocol'

export const swarmApi = {
  submitPrompt: (
    sessionId: string,
    prompt: string,
    attachments?: Attachment[],
    options?: RunOptions
  ): Promise<SubmitPromptResult> => window.swarm.submitPrompt(sessionId, prompt, attachments, options),
  cancelRun: (sessionId: string, runId: string): Promise<void> => window.swarm.cancelRun(sessionId, runId),
  interruptWith: (sessionId: string, runId: string): Promise<void> => window.swarm.interruptWith(sessionId, runId),
  decidePermission: (sessionId: string, actionId: string, decision: PermissionDecision): Promise<void> =>
    window.swarm.decidePermission(sessionId, actionId, decision),
  subscribeEvents: (cb: (e: UIEvent) => void): (() => void) => window.swarm.subscribeEvents(cb),
  onNavigateToSession: (cb: (sessionId: string) => void): (() => void) => window.swarm.onNavigateToSession(cb),
  onNavigateToSettings: (cb: (route: string) => void): (() => void) => window.swarm.onNavigateToSettings(cb),
  consumePendingDeepLink: (): Promise<{ sessionId: string } | null> => window.swarm.consumePendingDeepLink(),
  listSessions: (): Promise<SessionSummary[]> => window.swarm.sessions.list(),
  createSession: (): Promise<{ sessionId: string }> => window.swarm.sessions.create(),
  getRunEvents: (sessionId: string): Promise<import('@swarm/protocol').RunEvent[]> =>
    window.swarm.sessions.getRunEvents(sessionId),
  deleteSession: (sessionId: string): Promise<void> => window.swarm.sessions.delete(sessionId),
  renameSession: (sessionId: string, title: string): Promise<void> => window.swarm.sessions.rename(sessionId, title),
  setSessionPinned: (sessionId: string, pinned: boolean): Promise<void> =>
    window.swarm.sessions.setPinned(sessionId, pinned),
  updateSessionSettings: (sessionId: string, settings: SessionSettings): Promise<void> =>
    window.swarm.sessions.updateSettings(sessionId, settings),
  reorderSessions: (orderedIds: string[]): Promise<void> => window.swarm.sessions.reorder(orderedIds),
  listMemory: (namespace?: string): Promise<MemoryView[]> => window.swarm.memory.list(namespace),
  listAgents: (): Promise<AgentListItem[]> => window.swarm.agents.list(),
  saveAgent: (def: AgentDefinition): Promise<AgentMutationResult> => window.swarm.agents.save(def),
  removeAgent: (id: string): Promise<AgentMutationResult> => window.swarm.agents.remove(id),
  restoreDefaultAgents: (): Promise<AgentMutationResult> => window.swarm.agents.restoreDefaults(),
  getUsageStats: (rangeDays: number): Promise<UsageStats> => window.swarm.usage.get(rangeDays),
  getTrendingRepos: (period: TrendingPeriod, language: string): Promise<TrendingRepo[]> =>
    window.swarm.trending.get(period, language),
  researchRepo: (repo: TrendingRepo, period: TrendingPeriod): Promise<ResearchRepoResult> =>
    window.swarm.trending.research(repo, period),
  getRepoResearch: (repoName: string): Promise<{ research: RepoResearch | null; researchedAt: string | null }> =>
    window.swarm.trending.getResearch(repoName),
  researchedRepoNames: (): Promise<string[]> => window.swarm.trending.researchedNames(),
  getBilibiliStatus: (): Promise<BiliLoginStatus> => window.swarm.bilibili.status(),
  bilibiliLogin: (): Promise<BiliLoginStatus> => window.swarm.bilibili.login(),
  bilibiliLogout: (): Promise<void> => window.swarm.bilibili.logout(),
  getBilibiliList: (): Promise<BiliListResult> => window.swarm.bilibili.list(),
  bilibiliProcess: (bvid: string): Promise<BiliProcessResult> => window.swarm.bilibili.process(bvid),
  bilibiliOpen: (bvid: string): Promise<void> => window.swarm.bilibili.open(bvid),
  bilibiliGetObsidianConfig: (): Promise<ObsidianConfig | null> => window.swarm.bilibili.getObsidianConfig(),
  bilibiliSetObsidianConfig: (cfg: ObsidianConfig): Promise<void> => window.swarm.bilibili.setObsidianConfig(cfg),
  bilibiliPickVault: (): Promise<string | null> => window.swarm.bilibili.pickVault(),
  bilibiliSave: (video: BiliVideo, summary: BiliSummary): Promise<BiliSaveResult> =>
    window.swarm.bilibili.save(video, summary),
  bilibiliGetTranscribeConfig: (): Promise<TranscriptionConfig | null> => window.swarm.bilibili.getTranscribeConfig(),
  bilibiliSetTranscribeConfig: (cfg: TranscriptionConfig): Promise<void> =>
    window.swarm.bilibili.setTranscribeConfig(cfg),
  bilibiliPickModelDir: (): Promise<string | null> => window.swarm.bilibili.pickModelDir(),
  bilibiliTranscribe: (bvid: string): Promise<BiliTranscribeResult> => window.swarm.bilibili.transcribe(bvid),
  bilibiliOnTranscribeProgress: (cb: (p: BiliTranscribeProgress) => void): (() => void) =>
    window.swarm.bilibili.onTranscribeProgress(cb),
  bilibiliAnalyzedBvids: (): Promise<string[]> => window.swarm.bilibili.analyzedBvids(),
  bilibiliGetAnalysis: (bvid: string): Promise<BiliAnalysis | null> => window.swarm.bilibili.getAnalysis(bvid),
  bilibiliDeleteWatchLater: (bvid: string): Promise<BiliDeleteResult> => window.swarm.bilibili.deleteWatchLater(bvid),
  bilibiliDeleteFav: (video: BiliVideo): Promise<BiliDeleteResult> => window.swarm.bilibili.deleteFav(video),
  bilibiliArchiveList: (): Promise<BiliVideo[]> => window.swarm.bilibili.archiveList(),
  bilibiliArchivePut: (video: BiliVideo): Promise<void> => window.swarm.bilibili.archivePut(video),
  bilibiliArchiveRemove: (bvid: string): Promise<void> => window.swarm.bilibili.archiveRemove(bvid),
  bilibiliPinsList: (): Promise<BiliVideo[]> => window.swarm.bilibili.pinsList(),
  bilibiliPinsPut: (video: BiliVideo): Promise<void> => window.swarm.bilibili.pinsPut(video),
  bilibiliPinsRemove: (bvid: string): Promise<void> => window.swarm.bilibili.pinsRemove(bvid),
  articleList: (): Promise<CollectedArticleWithAnalysis[]> => window.swarm.article.list(),
  articleAnalyze: (articleId: string): Promise<AnalyzeArticleResult> => window.swarm.article.analyze(articleId),
  articleGetAnalysis: (articleId: string): Promise<{ summary: ArticleSummary | null; analyzedAt: string | null }> =>
    window.swarm.article.getAnalysis(articleId),
  articleDelete: (articleId: string): Promise<void> => window.swarm.article.delete(articleId),
  analyzeThread: (input: AnalyzeThreadInput): Promise<AnalyzeThreadResult> => window.swarm.analyzeThread(input),
  gmailGetThreadAnalysis: (threadId: string): Promise<GmailThreadAnalysis | null> =>
    window.swarm.gmail.getThreadAnalysis(threadId),
  // Calendar (page-surface subset; settings-panel OAuth methods stay on window.swarm.calendar directly).
  calendarGetStatus: (): Promise<CalendarConfigView> => window.swarm.calendar.getStatus(),
  calendarListInRange: (fromMs: number, toMs: number): Promise<CalendarEvent[]> =>
    window.swarm.calendar.listInRange(fromMs, toMs),
  calendarCreateLocal: (input: CalendarLocalInput): Promise<CalendarEvent> => window.swarm.calendar.createLocal(input),
  calendarDeleteLocal: (id: string): Promise<boolean> => window.swarm.calendar.deleteLocal(id),
  calendarSyncNow: (): Promise<void> => window.swarm.calendar.syncNow(),
  calendarOnStateChanged: (cb: (view: CalendarConfigView) => void): (() => void) =>
    window.swarm.calendar.onStateChanged(cb),
  listCronJobsForSession: (sessionId: string): Promise<CronJobSummary[]> => window.swarm.cron.listForSession(sessionId),
  listAllCronJobs: (): Promise<ScheduledTask[]> => window.swarm.cron.listAll(),
  listAllCronRuns: (): Promise<CronRun[]> => window.swarm.cron.listAllRuns(),
  cancelCronJob: (id: string): Promise<void> => window.swarm.cron.cancel(id),
  exportSessionMarkdown: (sessionId: string): Promise<{ path: string }> =>
    window.swarm.exportSessionMarkdown(sessionId),
  listArtifacts: (opts?: { cwd?: string; query?: string; limit?: number }): Promise<ArtifactEntry[]> =>
    window.swarm.listArtifacts(opts),
}
