onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
electron_mirror: https://npmmirror.com/mirrors/electron/
electron_builder_binaries_mirror: https://npmmirror.com/mirrors/electron-builder-binaries/
shamefullyHoist: true
allowBuilds:
  '@google/genai': false
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: false
patchedDependencies:
  better-sqlite3@12.10.0: patches/better-sqlite3@12.10.0.patch
