packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

overrides:
  '@types/react': '19.2.17'
  '@types/react-dom': '19.2.3'

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
shamefullyHoist: true
allowBuilds:
  '@google/genai': false
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: false
  spawn-sync: true
