/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes-settings/__root'
import { Route as WebSearchRouteImport } from './routes-settings/web-search'
import { Route as ProvidersRouteImport } from './routes-settings/providers'
import { Route as PermissionsRouteImport } from './routes-settings/permissions'
import { Route as McpRouteImport } from './routes-settings/mcp'
import { Route as AboutRouteImport } from './routes-settings/about'
import { Route as IndexRouteImport } from './routes-settings/index'

const WebSearchRoute = WebSearchRouteImport.update({
  id: '/web-search',
  path: '/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/permissions': typeof PermissionsRoute
  '/providers': typeof ProvidersRoute
  '/web-search': typeof WebSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/permissions': typeof PermissionsRoute
  '/providers': typeof ProvidersRoute
  '/web-search': typeof WebSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/permissions': typeof PermissionsRoute
  '/providers': typeof ProvidersRoute
  '/web-search': typeof WebSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/mcp'
    | '/permissions'
    | '/providers'
    | '/web-search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/mcp' | '/permissions' | '/providers' | '/web-search'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/mcp'
    | '/permissions'
    | '/providers'
    | '/web-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  McpRoute: typeof McpRoute
  PermissionsRoute: typeof PermissionsRoute
  ProvidersRoute: typeof ProvidersRoute
  WebSearchRoute: typeof WebSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-search': {
      id: '/web-search'
      path: '/web-search'
      fullPath: '/web-search'
      preLoaderRoute: typeof WebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  McpRoute: McpRoute,
  PermissionsRoute: PermissionsRoute,
  ProvidersRoute: ProvidersRoute,
  WebSearchRoute: WebSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
